### ISSUE TITLE
sudo wheel

### ISSUE THREAD

**Issue by haraldh** [npmccallum/ipxe#2]
I don't think this is necessary, because it is the default anyway.

https://github.com/npmccallum/ipxe/blob/286905f2e4d95c04547db45e81fc71d7a9463af5/enarx.ks#L51-L54

```console
$ sudo grep wheel /etc/sudoers
## Allows people in group wheel to run all commands
%wheel	ALL=(ALL)	ALL
```

**Comment by haraldh** [comment]
ah, oh.. sorry, you don't want no password... how unsecure.

**Comment by npmccallum** [comment]
> ah, oh.. sorry, you don't want no password... how unsecure.

It is a trade-off. Allowing password logins is also insecure given the army of bots out there trying to brute-force ssh logins.
